### PR TITLE
fix issue of finding instance

### PR DESCRIPTION
**Pull request by kaibocai**
fix https://github.com/microsoft/durabletask-java/issues/77

### CODE REVIEW

**Review by cgillum — APPROVED** [review]

**Comment by cgillum** [comment]
We should also fix the JavaDoc comment since it claims we return null, which isn’t accurate.

**Comment by kaibocai** [comment]
> We should also fix the JavaDoc comment since it claims we return null, which isn’t accurate.

I found update the method logic to align with the document make more sense to me. Please checkout the updated method. Thank you.

**Comment by kaibocai** [comment]
> > We should also fix the JavaDoc comment since it claims we return null, which isn’t accurate.
> 
> I found update the method logic to align with the document make more sense to me. Please checkout the updated method. Thank you.

I think I am wrong, this will also required to update our sample in our official document. Will revoke the commit and update the java doc accordingly.

**Review by cgillum — APPROVED** [review]
LGTM!

**Pull request merged**
